GET http://localhost:5000/report/generate-pdf
Content-Type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyMDRjOTU3ODQ2YmVmNDY3OTNkZjg2ZiIsImZpcnN0TmFtZSI6IkFLU0hBWSBLVU1BUiIsImxhc3ROYW1lIjoiU0lOR0giLCJ1c2VybmFtZSI6ImFrc2hheW1lbWFpbCIsInBhc3N3b3JkIjoiJDJiJDEwJHJqN3BldTYxcXhsNEZYMk94TThIWC5XZWFleS83Z2FQUTc3T2R1S0kvNzlGeXRqZmpWNFZXIiwiZm9ybXMiOltdLCJfX3YiOjB9LCJpYXQiOjE2NDQ0ODA4NjcsImV4cCI6MTY0NzA3Mjg2N30.bQFBpc_S8J3XAE2-sd_qz5vH1jh9YuNp5zfKR_ud314