POST http://localhost:5000/report/generate-pdf
Content-Type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyMDRjZWViZWFlMDEwOGE4ODVkYWFmZSIsImZpcnN0TmFtZSI6ImFtaXQiLCJsYXN0TmFtZSI6InNpbmdoIiwidXNlcm5hbWUiOiJhbWl0IiwicGFzc3dvcmQiOiIkMmIkMTAkd3dCeldMcDVHTWlwME5xei5pTGdwZUVQR2FwVG9LY1UuVUlsR28zYWFOVFouN3ROSVFTUmUiLCJmb3JtcyI6W10sIl9fdiI6MH0sImlhdCI6MTY0NDQ4MjI5NSwiZXhwIjoxNjQ3MDc0Mjk1fQ.DXhqO0HCeIJ5WStl0AP15agisA66FG7Y-s7LQxfZc8c

{
    "formid" : "0LeWtwwzpHIhJEFfK9LoR"
}